### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [seomoz/reppy#124]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.3.5. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary reppy2 -w /tmp/ext reppy2==0.3.5
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting reppy2==0.3.5
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/6f2/4d760a9389276/reppy2-0.3.5.tar.gz (10 kB)
Collecting python-dateutil
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/75b/b3f31ea686f11/python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
  Saved /tmp/ext/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting requests
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/439/99036bfa82904/requests-2.23.0-py2.py3-none-any.whl (58 kB)
  Saved /tmp/ext/requests-2.23.0-py2.py3-none-any.whl
Collecting url
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/8c6/e4a117bfc1566/url-0.4.2.tar.gz (140 kB)
Collecting six>=1.5
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/8f3/cd2e254d8f793/six-1.14.0-py2.py3-none-any.whl (10 kB)
  Saved /tmp/ext/six-1.14.0-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/fc3/23ffcaeaed0e0/chardet-3.0.4-py2.py3-none-any.whl (133 kB)
  Saved /tmp/ext/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<3,>=2.5
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/a06/8a21ceac8a4d6/idna-2.9-py2.py3-none-any.whl (58 kB)
  Saved /tmp/ext/idna-2.9-py2.py3-none-any.whl
Collecting certifi>=2017.4.17
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/1d9/87a998c75633c/certifi-2020.4.5.1-py2.py3-none-any.whl (157 kB)
  Saved /tmp/ext/certifi-2020.4.5.1-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/882/06b0eb87e6d67/urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
  Saved /tmp/ext/urllib3-1.25.9-py2.py3-none-any.whl
Skipping python-dateutil, due to already being wheel.
Skipping requests, due to already being wheel.
Skipping six, due to already being wheel.
Skipping chardet, due to already being wheel.
Skipping idna, due to already being wheel.
Skipping certifi, due to already being wheel.
Skipping urllib3, due to already being wheel.
Building wheels for collected packages: reppy2, url
  Building wheel for reppy2 (setup.py): started
  Building wheel for reppy2 (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /tmp/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-k26q4ofp/reppy2/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-k26q4ofp/reppy2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-r1w3b7xn
       cwd: /tmp/pip-wheel-k26q4ofp/reppy2/
  Complete output (32 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/reppy
  copying reppy/exceptions.py -> build/lib/reppy
  copying reppy/cache.py -> build/lib/reppy
  copying reppy/__init__.py -> build/lib/reppy
  copying reppy/parser.py -> build/lib/reppy
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/reppy
  copying build/lib/reppy/parser.py -> build/bdist.linux-x86_64/wheel/reppy
  copying build/lib/reppy/__init__.py -> build/bdist.linux-x86_64/wheel/reppy
  copying build/lib/reppy/cache.py -> build/bdist.linux-x86_64/wheel/reppy
  copying build/lib/reppy/exceptions.py -> build/bdist.linux-x86_64/wheel/reppy
  running install_egg_info
  running egg_info
  writing reppy2.egg-info/PKG-INFO
  writing dependency_links to reppy2.egg-info/dependency_links.txt
  writing requirements to reppy2.egg-info/requires.txt
  writing top-level names to reppy2.egg-info/top_level.txt
  warning: Failed to find the configured license file 'LICENSE'
  reading manifest file 'reppy2.egg-info/SOURCES.txt'
  writing manifest file 'reppy2.egg-info/SOURCES.txt'
  Copying reppy2.egg-info to build/bdist.linux-x86_64/wheel/reppy2-0.3.5.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: 'LICENSE'
  ----------------------------------------
  ERROR: Failed building wheel for reppy2
  Running setup.py clean for reppy2
  Building wheel for url (setup.py): started
  Building wheel for url (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /tmp/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-k26q4ofp/url/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-k26q4ofp/url/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-657k0jvw
       cwd: /tmp/pip-wheel-k26q4ofp/url/
  Complete output (258 lines):
  Building from C++
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/url
  copying url/__init__.py -> build/lib.linux-x86_64-3.8/url
  creating build/lib.linux-x86_64-3.8/url/psl
  copying url/psl/2016-08-16.psl -> build/lib.linux-x86_64-3.8/url/psl
  running build_ext
  building 'url.url' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/url
  creating build/temp.linux-x86_64-3.8/url/url-cpp
  creating build/temp.linux-x86_64-3.8/url/url-cpp/src
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Iurl/url-cpp/include -I/tmp/venv/include -I/usr/include/python3.8 -c url/url-cpp/src/url.cpp -o build/temp.linux-x86_64-3.8/url/url-cpp/src/url.o -std=c++11
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Iurl/url-cpp/include -I/tmp/venv/include -I/usr/include/python3.8 -c url/url-cpp/src/utf8.cpp -o build/temp.linux-x86_64-3.8/url/url-cpp/src/utf8.o -std=c++11
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Iurl/url-cpp/include -I/tmp/venv/include -I/usr/include/python3.8 -c url/url-cpp/src/punycode.cpp -o build/temp.linux-x86_64-3.8/url/url-cpp/src/punycode.o -std=c++11
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Iurl/url-cpp/include -I/tmp/venv/include -I/usr/include/python3.8 -c url/url-cpp/src/psl.cpp -o build/temp.linux-x86_64-3.8/url/url-cpp/src/psl.o -std=c++11
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Iurl/url-cpp/include -I/tmp/venv/include -I/usr/include/python3.8 -c url/url.cpp -o build/temp.linux-x86_64-3.8/url/url.o -std=c++11
  url/url.cpp: In function ‘PyObject* PyInit_url()’:
  url/url.cpp:10054:34: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10054 |   __pyx_type_3url_3url_StringURL.tp_print = 0;
        |                                  ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10054:34: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10054 |   __pyx_type_3url_3url_StringURL.tp_print = 0;
        |                                  ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10054:34: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10054 |   __pyx_type_3url_3url_StringURL.tp_print = 0;
        |                                  ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10059:35: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10059 |   __pyx_type_3url_3url_UnicodeURL.tp_print = 0;
        |                                   ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10059:35: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10059 |   __pyx_type_3url_3url_UnicodeURL.tp_print = 0;
        |                                   ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10059:35: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10059 |   __pyx_type_3url_3url_UnicodeURL.tp_print = 0;
        |                                   ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10063:52: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10063 |   __pyx_type_3url_3url___pyx_scope_struct__deparam.tp_print = 0;
        |                                                    ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10063:52: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10063 |   __pyx_type_3url_3url___pyx_scope_struct__deparam.tp_print = 0;
        |                                                    ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10063:52: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10063 |   __pyx_type_3url_3url___pyx_scope_struct__deparam.tp_print = 0;
        |                                                    ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10066:53: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10066 |   __pyx_type_3url_3url___pyx_scope_struct_1_genexpr.tp_print = 0;
        |                                                     ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10066:53: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10066 |   __pyx_type_3url_3url___pyx_scope_struct_1_genexpr.tp_print = 0;
        |                                                     ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10066:53: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10066 |   __pyx_type_3url_3url___pyx_scope_struct_1_genexpr.tp_print = 0;
        |                                                     ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10069:59: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10069 |   __pyx_type_3url_3url___pyx_scope_struct_2_filter_params.tp_print = 0;
        |                                                           ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10069:59: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10069 |   __pyx_type_3url_3url___pyx_scope_struct_2_filter_params.tp_print = 0;
        |                                                           ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10069:59: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10069 |   __pyx_type_3url_3url___pyx_scope_struct_2_filter_params.tp_print = 0;
        |                                                           ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10072:53: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10072 |   __pyx_type_3url_3url___pyx_scope_struct_3_genexpr.tp_print = 0;
        |                                                     ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10072:53: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10072 |   __pyx_type_3url_3url___pyx_scope_struct_3_genexpr.tp_print = 0;
        |                                                     ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10072:53: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10072 |   __pyx_type_3url_3url___pyx_scope_struct_3_genexpr.tp_print = 0;
        |                                                     ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10075:53: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10075 |   __pyx_type_3url_3url___pyx_scope_struct_4_genexpr.tp_print = 0;
        |                                                     ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10075:53: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10075 |   __pyx_type_3url_3url___pyx_scope_struct_4_genexpr.tp_print = 0;
        |                                                     ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp:10075:53: warning: ‘_typeobject::tp_print’ is deprecated [-Wdeprecated-declarations]
  10075 |   __pyx_type_3url_3url___pyx_scope_struct_4_genexpr.tp_print = 0;
        |                                                     ^~~~~~~~
  In file included from /usr/include/python3.8/object.h:746,
                   from /usr/include/python3.8/pytime.h:6,
                   from /usr/include/python3.8/Python.h:85,
                   from url/url.cpp:4:
  /usr/include/python3.8/cpython/object.h:260:30: note: declared here
    260 |     Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
        |                              ^~~~~~~~
  url/url.cpp: In function ‘void __Pyx__ExceptionSwap(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
  url/url.cpp:12497:24: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
  12497 |     tmp_type = tstate->exc_type;
        |                        ^~~~~~~~
        |                        curexc_type
  url/url.cpp:12498:25: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
  12498 |     tmp_value = tstate->exc_value;
        |                         ^~~~~~~~~
        |                         curexc_value
  url/url.cpp:12499:22: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
  12499 |     tmp_tb = tstate->exc_traceback;
        |                      ^~~~~~~~~~~~~
        |                      curexc_traceback
  url/url.cpp:12500:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
  12500 |     tstate->exc_type = *type;
        |             ^~~~~~~~
        |             curexc_type
  url/url.cpp:12501:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_value’; did you mean ‘curexc_value’?
  12501 |     tstate->exc_value = *value;
        |             ^~~~~~~~~
        |             curexc_value
  url/url.cpp:12502:13: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?
  12502 |     tstate->exc_traceback = *tb;
        |             ^~~~~~~~~~~~~
        |             curexc_traceback
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for url
  Running setup.py clean for url
Failed to build reppy2 url
ERROR: Failed to build one or more wheels
```

**Comment by wumpus** [comment]
This is a dup of issue #122

**Comment by thatch** [comment]
Most of the error is, but the line `error: [Errno 2] No such file or directory: 'LICENSE'` is the one that I was looking for.  I think this is on 3.8.2 btw

**Comment by wumpus** [comment]
Ah, indeed, the LICENSE thing is not Cython-related.

BTW my travis-ci build with 3.8 doesn't get any Cython complaints. It is 3.8.0.
